# fly.toml app configuration file generated for hello-fly-crimson-water-1026 on 2025-10-26T13:16:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'joyce-e-store'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[experimental]
  auto_rollback = true
  enable_consul = false
  ipv6 = false